name: Build qmlls

on:
  push:

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ubuntu
            os:   ubuntu-latest
          - name: macos
            os:   macos-latest
          - name: windows
            os:   windows-latest
    runs-on: ${{ matrix.os }}

    steps:
    - name: Create info file
      run: |
        echo -e "commit: $GITHUB_SHA\nbuild: $(date +"%Y-%m-%dT%H:%M:%SZ")" \
        > info.txt

    - uses: actions/checkout@v4
      with:
        path: source

    - name: Get current SHA
      id: vars
      working-directory: source
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Configure and build
      run:  |
        mkdir build
        echo testArtifact > build/qmlls

    - name: Zip build files in archive
      run: 7z a qmlls-${{ matrix.name }}-${{ steps.vars.outputs.sha_short }}.7z build/qmlls* info.txt

    - name: Upload archive
      uses: actions/upload-artifact@v4
      with:
        path: qmlls-${{ matrix.name }}-${{ steps.vars.outputs.sha_short }}.7z
        name: qmlls-${{ matrix.name }}-${{ steps.vars.outputs.sha_short }}.7z

  nightly-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4
      with:
        path: source

    - name: Get current SHA
      id: vars
      working-directory: source
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Download artifacts
      id: downloaded_artifacts
      uses: actions/download-artifact@v4
      with:
        path: release

    - name: Create nightly release
      if: ${{ ! contains(github.ref, 'tags/v') }}
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: qmlls-nightly-${{ steps.vars.outputs.sha_short }}
        draft: false
        prerelease: true
        files: release/*/*.7z

    - name: Create release
      if: ${{ contains(github.ref, 'tags/qmlls-') && !contains(github.ref, 'nightly') }}
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: qmlls-${{ steps.vars.outputs.sha_short }}
        draft: true
        prerelease: false
        files: release/*/*.7z
